[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Ensure Git LFS files are properly handled
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Explicitly tell Netlify to use Git LFS
[git]
  lfs = true 

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"

[[redirects]]
  from = "/invite/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/tasks/*"
  to = "/index.html"
  status = 200