[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Ensure Git LFS files are properly handled
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Explicitly tell Netlify to use Git LFS
[git]
  lfs = true 